name: carnd-term1
channels:
    - https://conda.anaconda.org/menpo
    - conda-forge
dependencies:
    - python==3.6.5
    - numpy
    - matplotlib
    - jupyter
    - pillow
    - scikit-learn
    - scikit-image
    - scipy
    - h5py
    - eventlet
    - flask-socketio
    - seaborn
    - pandas
    - ffmpeg
    - imageio=2.4.1
    - pyqt=5.9.2
    - pip:
        - moviepy
        - opencv-python
        - requests
        - tensorflow==1.12.0
        - keras==2.2.4
